
post_install() {
	echo -n "Adding aria2c user and group ..."
	# --no-create-home
	useradd aria2c -d /var/aria2c -U -s /bin/nologin && echo " done."
	passwd -l aria2c &>/dev/null

	chown aria2c:aria2c /etc/conf.d/aria2c-evn.conf
	chmod 600 /etc/conf.d/aria2c-evn.conf

	touch /var/aria2c/aria2c.log
	touch /var/aria2c/aria2c.session
	touch /var/aria2c/aria2c.log
}

post_remove() {
	echo -n -e "\nRemoving aria2c user/group..."
	userdel aria2c && echo " done."
}
